= API key policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-apikey/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-apikey/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^|

|===

== Description

You can use the `api-key` policy to enforce API key checks during request processing, allowing only apps with approved API
keys to access your APIs.

This policy ensures that API keys are valid, have not been revoked or expired and are approved to consume the specific
resources associated with your API.

=== Policy identifier

You can enable or disable the policy with policy identifier `api-key`.

== Configuration

=== Policy
You can configure the following policy level options:

|===
|Property |Required |Description |Type |Default

.^|`propagateApiKey`
^.^|-
|Propagate API key to upstream API
^.^|boolean
^.^|_false_

|===


[source, json]
.Configuration
----
"api-key": {
  "propagateApiKey": false
}
----

=== Gateway
You can also configure the policy in the APIM Gateway configuration file (`gravitee.yml`).
You can customize the `X-Gravitee-Api-Key` header and `api-key` query parameter.

[source, yaml]
.Configuration
----
policy:
  api-key:
    header: My-Custom-Api-Key
    param: custom-api-key
----

== Errors
You can use the link:/apim/3.x/apim_publisherguide_response_templates[response templates^] feature to override the default response provided by the policy. These templates must be defined at the level of the API.

The error keys sent by this policy are as follows:

[cols="2*", options="header"]
|===
^|Key
^|Parameters

.^|API_KEY_MISSING
^.^|-
.^|API_KEY_INVALID_KEY
^.^|-

|===
